FORMAT: 1A9

# Data Structures

## Campus (object)

+ name: 河南工业大学 (string) - 学校名称

## Academy (object)

+ name: 信息科学与工程 (string) - 学院名称

## Profession (object)

+ name: 软件工程 (string) - 专业名称



# Group 学校班级信息

对学校，学院，专业，班级的设置、更新与查找

## 学校 [/admin/api/campuses]

### 新建一个高校 [POST]

- Request

    + Attributes (Campus)

- Response 200

        {
            "code": 0,
            "data": {
                "version": 0,
                "id": 1,
                "name": "河南工业大学",
                "updatedAt": "2017-07-18T13:53:55.951Z",
                "createdAt": "2017-07-18T13:53:55.951Z"
            }
        }

- Response 200

        {
            "code": 1,
            "msg": "学校已存在"
        }

- Response 200

        {
            "code": 2,
            "msg": "无权限"
        }

### 获取全部高校 [GET]

- Response 200

        {
            "code": 0,
            "data": [
                {
                    "id": 1,
                    "name": "河南工业大学"
                },
                {
                    "id": 2,
                    "name": "郑州大学"
                }
            ]
        }

## 学院 [/admin/api/academies{?cid}]

### 新建一个学院 [POST]

- Request

    + Attributes (Academy)

- Response 200

        {
            "code": 0,
            "data": {
                "version": 0,
                "id": 3,
                "name": "信息科学与工程",
                "cid": 1,
                "updatedAt": "2017-07-23T09:29:43.983Z",
                "createdAt": "2017-07-23T09:29:43.983Z"
            }
        }

- Response 200

        {
            "code": 1,
            "msg": "学院已存在"
        }

- Response 200

        {
            "code": 2,
            "msg": "无权限"
        }

### 获取学校下的全部学院 [GET]

- Parameters
    + cid: 1 (number) - 高校id

- Response 200

        {
            "code": 0,
            "data": [
                {
                    "id": 3,
                    "name": "信息科学与工程"
                },
                {
                    "id": 4,
                    "name": "新闻与传播"
                }
            ]
        }

## 专业 [/admin/api/professions{?aid}]

### 新建一个专业 [POST]

- Request

    + Attributes (Profession)

- Response 200

        {
            "code": 0,
            "data": {
                "version": 0,
                "id": 1,
                "name": "软件工程",
                "aid": 3,
                "updatedAt": "2017-07-23T10:08:44.277Z",
                "createdAt": "2017-07-23T10:08:44.277Z"
            }
        }

- Response 200

        {
            "code": 1,
            "msg": "专业已存在"
        }

- Response 200

        {
            "code": 2,
            "msg": "无权限"
        }

### 获取学院下的全部专业 [GET]

- Parameters
    + aid: 1 (number) - 学院id

- Response 200

        {
            "code": 0,
            "data": [
                {
                    "id": 1,
                    "name": "软件工程"
                },
                {
                    "id": 2,
                    "name": "计算机科学与技术"
                }
            ]
        }

        
